############# USER #############
# POST http://localhost:4000/api/user/signup/
# Content-Type: application/json

# {
#     "user": 2345
# }

###
# POST http://localhost:4000/api/user/login/
# Content-Type: application/json

# {
#     "user": 1234
# }

############# TODO LIST #############

### ERROR ###
# POST http://localhost:4000/api/todolist/item/
# Content-Type: application/json

# {
# "item": "ini adalah Todo List dari Mock Up test",
# "user_id": "6398541eae1b40394e225b65"
# }

###

### POST AN ITEM SUCCESS ###
# POST http://localhost:4000/api/todolist/item/
# Content-Type: application/json

# {
#     "item": "This is the fourth thing to do"
# }

###

### GET ALL ITEMS SUCCESS ###
# GET http://localhost:4000/api/todolist/items/ 
# Content-Type: application/json

###

### GET A SINGLE ITEM SUCCESS ###
# GET http://localhost:4000/api/todolist/6399898b7f33b0d6e8cd2658 
# Content-Type: application/json

###

### UPDATE AN ITEM SUCCESS ###
# PATCH http://localhost:4000/api/todolist/item/63985edf29a5111e22cc2644
# Content-Type: application/json

# {
# "item": "Below is the things to do"
# }

###

### DELETE AN ITEM SUCCESS ###
# DELETE http://localhost:4000/api/todolist/item/639989957f33b0d6e8cd265c
# Content-Type: application/json

###
